import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "../globals.css";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import AuthLayoutImage from "@/public/auth-layout.png";
import Image from "next/image";
import { Toaster } from "@/components/ui/sonner";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${inter.variable} antialiased`}
      >
        <Card className="overflow-hidden min-h-screen">
          <CardContent className="grid p-0 md:grid-cols-2">
            <div className="relative hidden bg-[#F1F7FF] md:block h-screen">
              <div className="block-space big-container">
                <div className="flex justify-center">
                  <Button variant={"outline"} className="">
                    Developer API coming soon🚀
                  </Button>
                </div>
                <h1 className="font-plus-jakarta-sans text-center mt-4">
                  Transform your Unstructured Data into
                  <span className="bg-gradient-to-r from-[#757CFF] to-[#757CFF] bg-clip-text text-transparent  ">
                    Actionable Insights
                  </span>
                </h1>
                <p className="text-center mt-4 text-[rgba(0, 0, 0, 0.70)]">
                  Vision Language Model (VLM) powered structuring that
                  simplifies your data, saves time, and boosts efficiency.
                </p>
              </div>
              <div className="pr-12 md:pr-16 lg:pr-24">
                <img
                  src={AuthLayoutImage.src}
                  alt="Auth Layout Image"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            {children}
            <Toaster />
          </CardContent>
        </Card>
      </body>
    </html>
  );
};

export default layout;
