import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Card className="overflow-hidden min-h-screen">
          <CardContent className="grid p-0 md:grid-cols-2">
            <div className="relative hidden bg-muted md:block h-screen">
              <Button variant={"outline"}>Developer API coming soon🚀</Button>
              <h1>Transform your Unstructured Data into Actionable Insights</h1>
              <p>
                Vision Language Model (VLM) powered structuring that simplifies
                your data, saves time, and boosts efficiency.
              </p>
            </div>
            {children}
          </CardContent>
        </Card>
      </body>
    </html>
  );
};

export default layout;
